### PR TITLE
Replace LICENSE symlinks with an actual file

### LINKED ISSUE #37: setup.py creation fails silently
@tbetbetbe

### PR DESCRIPTION
**Pull request by tbetbetbe**
- This is because the LICENSE symlinks don't get packaged correctly when
  the npm package is published

Fixes #37

### CODE REVIEW

File: lib/packager.js [hunk 1]
```diff
@@ -93,6 +93,9 @@ function makeGolangPackage(opts, done) {
   opts.copyables.forEach(function(f) {
```
Comment (saicheems) [inline lib/packager.js]: on inspection... i feel like you can put function(f) in the parent scope and avoid a whole lot of repetition

**Comment by saicheems** [comment]
lgtm otherwise

File: lib/packager.js (hunk 1 above)
Comment (tbetbetbe) [inline lib/packager.js]: Passing through the enclosed variables makes setting that up a little bit more complex.
I.e, there'd need to be a function that returns f the parent scope, rather than f itself.
For now I'll leave as is, but we can revisit this later if the packager functions become more complex
