### PR TITLE
Display errors that occur during buildPackage

### LINKED ISSUE #37: setup.py creation fails silently
@tbetbetbe

### PR DESCRIPTION
**Pull request by tbetbetbe**
- these were being hidden, as the error ApiRepo 'error' event was not
  being triggered by buildPackage errors. This change corrects that.

Also:
 - removes some unnecessary trace in the java package builder

Fixes #37

### CODE REVIEW

File: lib/api_repo.js [hunk 1]
```diff
@@ -240,7 +250,17 @@ ApiRepo.prototype.buildCommonProtoPkgs =
   function buildCommonProtoPkgs(opt_done) {
     var tasks = [];
     var that = this;
-    var done = opt_done || _.noop;
+
+    /** done emits errors that occur during processing */
+    var done = function done(err) {
```
Comment (saicheems) [inline lib/api_repo.js]: does this have to be defined twice?

**Comment by saicheems** [comment]
lgtm otherwise

File: lib/api_repo.js (hunk 1 above)
Comment (tbetbetbe) [inline lib/api_repo.js]: Fixed
